#!/bin/sh

set -e

VIRTUALENV=".temptools/virtualenv/virtualenv.py"
REQUIREMENTSDEV="requirements-dev.txt"
REQUIREMENTS="requirements.txt"
if [ -e ~/.dev ]; then
    envtype="DEV"
else
    envtype="REAL"
fi

if [ "$1" ]; then
    action="$1"
else
    action="default"
fi

case "$action" in
    default)
        echo $envtype
        ;;
    isdev)
        if [ "$envtype" = "DEV" ]; then
            exit 0
        else
            exit 1
        fi
        ;;
    isreal)
        if [ "$envtype" = "REAL" ]; then
            exit 0
        else
            exit 1
        fi
        ;;
    requirements)
        pip_install="$2"
        if [ "$envtype" = "DEV" ]; then
            $pip_install -r $REQUIREMENTSDEV
        elif [ "$envtype" = "REAL" ]; then
            $pip_install -r $REQUIREMENTS
        fi
        ;;
    init_dev)
        if [ "$envtype" = "DEV" ]; then
            if [ ! -e "$2" ]; then
                python $VIRTUALENV "$2"
            fi
        fi
        ;;
esac
